import type { Metadata, Viewport } from 'next'

import { SafeAreaProvider } from './safe-area-provider'

import '../styles/main.css'

export const metadata: Metadata = {
  title: "Escobar's Steakhouse",
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="min-w-80 bg-background text-foreground antialiased my-safe">
        <div className="h-(--safe-area-inset-top) fixed inset-x-0 top-0 z-50 w-full bg-background"></div>
        <SafeAreaProvider>{children}</SafeAreaProvider>
      </body>
    </html>
  )
}
